### ISSUE TITLE
Font sizing depending on viewport width causes issues

### ISSUE THREAD

**Issue by QkeleQ10** [jkorb/logicalmethods.ai#19]
The following CSS rule present in `_utilities.scss` causes text in the slides to scale incorrectly:
```css
.fs-1 {
    font-size: calc(1.375rem + 1.5vw) !important;
}
```

This happens because a viewport unit (vw) is used, which depends on the width of the window.

This can be made clear by zooming in when viewing a fullscreen slide. The text shrinks due to the viewport width decreasing. Another example is making the window narrower.

A solution would be to set the font size to a value like `2rem`.
